# Generated by Django 2.2.12 on 2020-05-25 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200525_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-c_time'], 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AddField(
            model_name='users',
            name='c_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('1', 'booker'), ('2', 'host'), ('3', 'admin')], default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
