# Generated by Django 2.2.12 on 2020-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200525_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('1', 'booker'), ('2', 'host')], default='1', max_length=32),
        ),
    ]
