# Generated by Django 2.2.12 on 2020-05-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200526_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-c_time'], 'verbose_name': 'username', 'verbose_name_plural': 'username'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='type',
            new_name='usertype',
        ),
    ]
