# Generated by Django 2.2.12 on 2020-05-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200526_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='year',
        ),
        migrations.AlterModelTable(
            name='users',
            table='login_users',
        ),
    ]
