# Generated by Django 2.2.12 on 2020-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200526_1834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='login_users',
        ),
    ]
