# Generated by Django 2.2.12 on 2020-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200526_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
