# Generated by Django 2.2.12 on 2020-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_users_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.CharField(default='Nothing', max_length=500),
        ),
    ]
