# Generated by Django 2.2.12 on 2020-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(unique=True)),
                ('RID', models.IntegerField(unique=True)),
                ('book_id', models.IntegerField(unique=True)),
                ('indate', models.DateTimeField()),
                ('outdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
