# Generated by Django 2.2.12 on 2020-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_id',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user_id',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
