# Generated by Django 2.2.12 on 2020-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200526_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_id',
            name='UID',
            field=models.IntegerField(unique=True),
        ),
    ]
