# Generated by Django 2.2.12 on 2020-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20200526_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_id',
            name='email',
            field=models.EmailField(default=0, max_length=40, unique=True),
        ),
    ]
