# Generated by Django 2.2.12 on 2020-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20200527_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_id',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
