# Generated by Django 2.2.12 on 2020-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20200527_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_id',
            name='email',
            field=models.EmailField(default=0, max_length=40),
        ),
    ]
