# Generated by Django 2.2.12 on 2020-05-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_auto_20200528_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='outdate',
        ),
    ]
