# Generated by Django 2.2.12 on 2020-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('about', models.TextField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField(unique=True)),
                ('street', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField(unique=True)),
                ('RID', models.IntegerField(unique=True)),
                ('update_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
