# Generated by Django 2.2.12 on 2020-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200526_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
