# Generated by Django 2.2.12 on 2020-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200526_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_info',
            name='email',
            field=models.EmailField(default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
