# Generated by Django 2.2.12 on 2020-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_host_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='about',
            field=models.CharField(default='Nothing', max_length=500),
        ),
    ]
