# Generated by Django 2.2.12 on 2020-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200527_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='about',
            field=models.CharField(default='Nothing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='host_info',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
