# Generated by Django 2.2.12 on 2020-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20200527_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='about',
            field=models.CharField(default='Nothing', max_length=2000),
        ),
    ]
