# Generated by Django 2.2.12 on 2020-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20200527_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='about',
            field=models.TextField(default='Nothing'),
        ),
    ]
