# Generated by Django 2.2.12 on 2020-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20200527_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
