# Generated by Django 2.2.12 on 2020-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20200527_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='HID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
