# Generated by Django 2.2.12 on 2020-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_listing_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_info',
            name='statement',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='statement',
            field=models.IntegerField(default=1),
        ),
    ]
