# Generated by Django 2.2.12 on 2020-05-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField(unique=True)),
                ('UID', models.IntegerField(unique=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='room_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('accommodates', models.IntegerField()),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('amenities', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
