# Generated by Django 2.2.12 on 2020-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_info',
            name='image_url',
            field=models.URLField(blank=True, default=' '),
        ),
    ]
