# Generated by Django 2.2.12 on 2020-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_room_info_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='RID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='UID',
            field=models.IntegerField(),
        ),
    ]
