# Generated by Django 2.2.12 on 2020-05-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20200527_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='RID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.room_info'),
        ),
    ]
