# Generated by Django 2.2.12 on 2020-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_auto_20200527_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='RID',
            new_name='RID_id',
        ),
    ]
