# Generated by Django 2.2.12 on 2020-05-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0010_remove_rating_rid_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
    ]
