# Generated by Django 2.2.12 on 2020-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0012_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='RID',
            new_name='RID_id',
        ),
        migrations.AlterField(
            model_name='room_info',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
