# Generated by Django 2.2.12 on 2020-05-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0013_auto_20200528_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='RID_id',
            new_name='RID',
        ),
    ]
