# Generated by Django 2.2.12 on 2020-05-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0014_auto_20200528_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_info',
        ),
    ]
