# Generated by Django 2.2.12 on 2020-05-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0016_room_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
    ]
